project_id = "tplwovotqrreelmquovj"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[[edge_functions]]
name = "analyze-document"
verify_jwt = true