// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tplwovotqrreelmquovj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwbHdvdm90cXJyZWVsbXF1b3ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5MjkxNzcsImV4cCI6MjA1MTUwNTE3N30.Jjrbx_E_Lz7cPgPPaZPVHrIZ4a06rZPgHEWGqJjJolk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);